name: mana_reader
description: A cross-platform manga and doujinshi reader.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  path: ^1.9.0
  http: ^1.1.0
  archive: ^4.0.7
  file_selector: ^1.0.3
  permission_handler: ^12.0.1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^1.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  native_pdf_renderer: ^6.0.0
  go_router: ^14.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
