name: mana_reader
description: A cross-platform manga and doujinshi reader.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.2
  path_provider: ^2.1.1

  path: ^1.9.0

  http: ^0.13.6
  file_picker: ^6.1.1
  archive: ^3.3.7
  rar: ^3.0.1
  pdf_render: ^1.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.3.6
  path_provider_platform_interface: any

flutter:
  uses-material-design: true
