diff --git a//dev/null b/mana_reader/.metadata
index 0000000000000000000000000000000000000000..af5cda898d59b82989070ecc2dbdbc4688de88f6 100644
--- a//dev/null
+++ b/mana_reader/.metadata
@@ -0,0 +1,45 @@
+# This file tracks properties of this Flutter project.
+# Used by Flutter tool to assess capabilities and perform upgrades etc.
+#
+# This file should be version controlled and should not be manually edited.
+
+version:
+  revision: "edada7c56edf4a183c1735310e123c7f923584f1"
+  channel: "stable"
+
+project_type: app
+
+# Tracks metadata for the flutter migrate command
+migration:
+  platforms:
+    - platform: root
+      create_revision: edada7c56edf4a183c1735310e123c7f923584f1
+      base_revision: edada7c56edf4a183c1735310e123c7f923584f1
+    - platform: android
+      create_revision: edada7c56edf4a183c1735310e123c7f923584f1
+      base_revision: edada7c56edf4a183c1735310e123c7f923584f1
+    - platform: ios
+      create_revision: edada7c56edf4a183c1735310e123c7f923584f1
+      base_revision: edada7c56edf4a183c1735310e123c7f923584f1
+    - platform: linux
+      create_revision: edada7c56edf4a183c1735310e123c7f923584f1
+      base_revision: edada7c56edf4a183c1735310e123c7f923584f1
+    - platform: macos
+      create_revision: edada7c56edf4a183c1735310e123c7f923584f1
+      base_revision: edada7c56edf4a183c1735310e123c7f923584f1
+    - platform: web
+      create_revision: edada7c56edf4a183c1735310e123c7f923584f1
+      base_revision: edada7c56edf4a183c1735310e123c7f923584f1
+    - platform: windows
+      create_revision: edada7c56edf4a183c1735310e123c7f923584f1
+      base_revision: edada7c56edf4a183c1735310e123c7f923584f1
+
+  # User provided section
+
+  # List of Local paths (relative to this file) that should be
+  # ignored by the migrate tool.
+  #
+  # Files that are not part of the templates will be ignored by default.
+  unmanaged_files:
+    - 'lib/main.dart'
+    - 'ios/Runner.xcodeproj/project.pbxproj'
